### ISSUE TITLE
Set up local Chef development environment (Vagrant and Virtualbox)

### ISSUE THREAD

**Issue by MichaelDepner** [Praqma/study-succotash#12]
Follow the tutorial at https://learn.chef.io/local-development/windows/get-set-up/get-set-up-vagrant/ to set up vagrant and virtualbox in order to run local windows hosts to deploy and test cookbooks on.

Note down any extra steps needed to make it work, or any other discoveries / best practices, so that others may benefit from it.

**Comment by MichaelDepner** [comment]
Scope of this changed a bit, as I was unsuccesful in getting vagrant to work (windows machine downloaded updates for 5 hours, then crashed in the end).
Chose to try out testkitchen with AWS instead, which worked right away, and without an enormous time investment.

**Comment by mortench3000** [comment]
The Vagrant/Windows Server crash was solved by setting headless=true in the packer file (vbox-2012r2.json). I am now running the image with Vagrant/TestKitchen.

**Comment by martinmosegaard** [comment]
@mortench3000 Can you add that to the learnings README?
