### ISSUE TITLE
Describe general approach for installing Windows packages

### ISSUE THREAD

**Issue by mortench3000** [Praqma/study-succotash#16]
Windows packages comes in many flavours. Describe how to approach Chef configuration management with a Windows package not supported by a package manager like Chocolatey, and not already in a community package (supermarket.chef.io)

**Comment by MichaelDepner** [comment]
Did some investigative work:

It seems very varied how big of a challenge it is to install programs. Some installers are as simple as:

```
 # install python 2.7
windows_package 'python 2.7' do
  source 'https://www.python.org/ftp/python/2.7.12/python-2.7.12.amd64.msi'
  installer_type :msi
  action :install
end

# add python 2.7 installation folder to path
windows_path 'C:\Python27' do
  action :add
end
```

Whereas for something like the Windows Driver Package it seems to require you to open the .exe and manually clicking the options you need, with seemingly no support for silent installation.

It's probably needed to go through the list of applications needed and determining how much work they require.

**Comment by martinmosegaard** [comment]
I had to install a package delivered as a WinZip self-extract archive. This was an `.exe` file, which when clicked would extract into a folder containing a `setup.exe` file which could then be run with silent install options.

Here is what I had to do (some details omitted):

``` sh
# Download exe/zip file
remote_file zip_path do
  source node['my_software'][version]['url']
  checksum node['my_software'][version]['sha256']
end

# Extract zip file using PowerShell 4.0 (PowerShell 5 has unzip, but is not on Win 2012)
powershell_script 'extract-zip' do
  code <<-EOF
  [System.Reflection.Assembly]::LoadWithPartialName("System.IO.Compression.FileSystem") | Out-Null
  [System.IO.Compression.ZipFile]::ExtractToDirectory("#{zip_path}", "#{extract_dir}")
  EOF
  creates extract_dir
end

windows_package 'package-name-to-ensure-idempotency' do
  source "#{extract_dir}/setup.exe"
  installer_type :custom

  options '/q' # etc.. the silent install options

  # The installer initiates a reboot. 1641 is the value of the
  # Windows Installer code ERROR_SUCCESS_REBOOT_INITIATED.
  returns [1641]
end
```

BTW:
The `windows` cookbook does have unzip functionality using `windows_zipfile`. However, I could not use that, because it would try to download a dependency gem inside the node. That did not work for me, because the node did not have access to rubygems.org

**Comment by buep** [comment]
Status on this one ? size is medium, yet 7,5 hours spent? Can it be closed? We need a commit in our repo about research or some examples
