### ISSUE TITLE
How-to use community cookbooks

### ISSUE THREAD

**Issue by mortench3000** [Praqma/study-succotash#2]
The supermarket (https://supermarket.chef.io/cookbooks) is packed with community cookbooks, but it is not exactly clear how to include them in your own recipies/cookbooks.
i.e. the java cookbook apparently does not work without setting/overriding options.

**Comment by mortench3000** [comment]
Chef Fundamentals Webinar on YouTube:
https://www.youtube.com/playlist?list=PLW2t3zpbZ8T8hoiIoRUS-nbgLuQ6QmAbb

**Comment by buep** [comment]
I guess this is done... so closing it.
