### ISSUE TITLE
MySQL cookbook 

### ISSUE THREAD

**Issue by timea** [Praqma/study-succotash#25]
It would be nice if we could deploy an updated scheme with the latest sql dump in it to our database servers. 

I have seen solutions out there, I would like to explore it to see how hard it is to utilize this way in setting up test databases for our pipelines.

**Comment by buep** [comment]
Which databases are we talking about? For database testing there seems to be much better tools related to test data management.
Chef doesn't seem like the obvious choice to me.

**Comment by timea** [comment]
I do not know an exact client or Praqma example, this is just something I want to know how to solve (MySQL is just a generic example). What would be the better way? I can see that chef can handle it, seen examples online, and seemed like a cheap way to do it as we know already how to use chef. I would love to know what would you use for this.

**Comment by buep** [comment]
For example Flyway is an obvious choice, as it is then handled by your build system: https://flywaydb.org/

In my opinion Chef is the wrong tool for handling data schemas and data for testing, there are more code centric tools like the one above.
Chef is good though to install the MySQL servers.

**Comment by timea** [comment]
Great, I will take a look at spinning up MySQL with Chef and flyway then (probably in the RnD repo in a new issue). Thanks @buep.

**Comment by buep** [comment]
Sorry, I don't really understand why MySQL suddenly is interesting as we have no-one using it and it is just an installation of a program like any other program.
Database roll-back and forward is interesting though, but not in the context of Chef.
Such tools belong to the program code, and the reason those tools are typically preferred are that the good ones of them understand the program and datamodel, thus automatically can adjust the database.

I see the next most important thing in our Chef research to be what are described by issues in this milestone: https://github.com/Praqma/study-succotash/milestone/3

Something about testing should be added to the milestone though - that is an important next step also.
